name             'cisco_imc_cookbook'
maintainer       'Cisco Systems Inc.'
maintainer_email 'amimanda@cisco.com'
license          'Apache-2.0'
description      'This cookbook configures Cisco IMC Servers(standalone)'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
chef_version '>= 12'
supports 'CentOS', '>=6.5'
supports 'ubuntu', '>=16.04'
source_url	'https://github.com/CiscoUcs/cisco_imc_cookbook'
issues_url	'https://github.com/CiscoUcs/cisco_imc_cookbook/issues'
version          '0.9.1'
